### PR TITLE
Fix segfaults somehow, don't know why this works...

### PR DESCRIPTION
**Pull request by WillemWybo**

### CODE REVIEW

**Comment by WillemWybo** [comment]
The `push_back()` to the synapse vectors as in lines 196,197 of the jijna `compartmentCurrentsHeader.jinja2` generates a segfault. 

This solution (line 198) fixes it somehow, but I have no clue why.

Also some minor changes to the variable names in the `receptor_params`

**Comment by pythonjam** [comment]
I'll merge it in for now. I don't have anything set up to debug the actual c++ code but I'll see if I have any ideas

**Comment by pythonjam** [comment]
from what I read so far looks like vector is making assumptions about the object you push into it, i.e it copies it internally etc. It may be a copy constructor / destructor issue

**Comment by pythonjam** [comment]
If you call it as you did in line 198, it's possible that the optimization of the compiler may be able to remove some unnecessary constructor calls, which otherwise cause the error. Just a plausible theory

**Comment by pythonjam** [comment]
I looked a little bit deeper and now i believe that std::shared_ptr< RingBuffer > b_spikes releases/destroys the RingBuffer while being copied into the vector

**Pull request merged**
